# Generated by Django 4.2.23 on 2025-10-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logingov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logingovspsettings',
            name='aal_level',
            field=models.CharField(
                choices=[
                    ('duo', 'Require basic two-factor authentication'),
                    ('separate', 'Require separate second factor (i.e., not a remembered device)'),
                    ('phishing_resistant', 'Require a phishing resistant second factor (WebAuthn or PIV/CAC)'),
                    ('require_hspd12', 'Require an HSPD12 credential (requires PIV/CAC)')
                ],
                default='duo',
                help_text='AAL level for authentication',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='logingovspsettings',
            name='ial_level',
            field=models.CharField(
                choices=[
                    ('auth-only', 'Authentication only'),
                    ('verified', 'Verified, no facial matching'),
                    ('verified-facial-match-preferred', 'Verified, facial match preferred'),
                    ('verified-facial-match-required', 'Verified, facial match required')
                ],
                default='auth-only',
                help_text='IAL level for authentication',
                max_length=31
            ),
        ),
        migrations.AddField(
            model_name='logingovspsettings',
            name='scopes',
            field=models.CharField(
                blank=True,
                help_text='The scopes to request from Login.gov." \
                    "The <code>email</code> scope is always requested.',
                max_length=255
            ),
        ),
        migrations.AlterField(
            model_name='logingovspsettings',
            name='auto_create_users',
            field=models.BooleanField(
                default=False,
                help_text='Automatically create new Django users when logging in via Login.gov'
            ),
        ),
        migrations.AlterField(
            model_name='logingovspsettings',
            name='auto_link_users',
            field=models.BooleanField(
                default=False,
                help_text='Automatically link existing Django users when logging in via Login.gov'
            ),
        ),
        migrations.AlterField(
            model_name='logingovspsettings',
            name='client_id',
            field=models.CharField(
                default=None,
                help_text='Client ID for Login.gov. In the Login.gov dashboard, this is called "Issuer" and will have the form '
                '<b>urn:gov:gsa:openidconnect.profiles:sp:sso:<i>agency_name</i>:<i>app_name</i></b>',
                max_length=255
            ),
        ),
    ]
