# Generated by Django 4.2.23 on 2025-10-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logingov', '0002_logingovspsettings_aal_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logingovspsettings',
            name='token_expire',
            field=models.IntegerField(
                default=300,
                help_text='Token expiration time in seconds (default: 300)'
            ),
        ),
    ]
